server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /ics/ {
        alias /usr/share/nginx/html/ics/;
        types { }
        default_type text/calendar;
        add_header Access-Control-Allow-Origin *;
    }
}
